name: Vulnerability Test Workflow

on:
  workflow_dispatch:
    inputs:
      userInput:
        description: 'User Input'
        required: true
        default: 'default value'

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        env:
          REPO_ORG: ${{ steps.set-repo-org.outputs.repoorg }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.create({
              owner: '${{ env.REPO_ORG }}',
              repo: 'django-DefectDojo',
              title: 'Release: Merge back ${{ github.event.inputs.userInput }} into dev from: ${{ env.NEW_BRANCH }}',
              body: `Release triggered by \`${ process.env.GITHUB_ACTOR }\``,
              head: '${{ env.NEW_BRANCH }}',
              base: 'dev'
            })



